spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quiz?useSSL=false
    username: root
    password: rivendel
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect